# Generated by Django 3.1 on 2020-02-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateTimeField()),
                ('done', models.BooleanField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task')),
            ],
        ),
    ]
