# Generated by Django 3.1 on 2020-02-08 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_block_on_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblock',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
