# Generated by Django 3.1 on 2020-02-08 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200208_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='subblock',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
