# Generated by Django 3.1 on 2020-02-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20200208_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='allow_all_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='allow_no_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='allow_only_tasks_with_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('blocks', models.ManyToManyField(to='todo.Block')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.User')),
                ('tasks', models.ManyToManyField(to='todo.Task')),
            ],
        ),
    ]
