# Generated by Django 3.1 on 2020-02-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20200208_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
        migrations.AddField(
            model_name='block',
            name='tags',
            field=models.ManyToManyField(to='todo.Tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='todo.Tag'),
        ),
    ]
