# Generated by Django 3.1 on 2020-04-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20200208_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='sub_block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.SubBlock'),
            preserve_default=False,
        ),
    ]
