# Generated by Django 3.1 on 2020-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_subtask_sub_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='assigned',
        ),
        migrations.AddField(
            model_name='subtask',
            name='duration',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
