# Generated by Django 3.1 on 2020-04-14 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20200409_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
