# Generated by Django 3.1 on 2020-04-14 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20200414_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
